blueprint:
  name: Fenster steuert Heizkörper (Area + Restore + Zigbee/Homematic)
  description: >
    Fenster auf: Modus speichern + OFF.
    Fenster zu: gespeicherten Modus wiederherstellen (auto/heat).
    Area-basiert, Zigbee-kompatibel, Homematic-kompatibel, Tuya-sicher.
  domain: automation

  input:
    fenster:
      name: Fensterkontakt
      selector:
        entity:
          domain: binary_sensor
          device_class:
            - window
            - door
            - opening

mode: parallel

trigger:
  - platform: state
    entity_id: !input fenster
    to:
      - "on"
      - "off"

action:
  - variables:
      fenster_entity: "{{ trigger.entity_id }}"
      fenster_area: "{{ area_id(fenster_entity) }}"
      area_entities_list: "{{ area_entities(fenster_area) }}"
      heizkoerper: >
        {{ area_entities_list
           | select('match', '^climate\\.')
           | list }}

  - service: system_log.write
    data:
      message: >
        RESTORE: Fenster={{ fenster_entity }} ({{ states(fenster_entity) }}),
        Area={{ fenster_area }},
        Heizkörper={{ heizkoerper }}
      level: info

  - choose:

      # ---------------------------------------------------------
      # FENSTER AUF → Modus speichern + OFF
      # ---------------------------------------------------------
      - conditions:
          - condition: state
            entity_id: !input fenster
            state: "on"
        sequence:
          - repeat:
              for_each: "{{ heizkoerper }}"
              sequence:
                - variables:
                    entity: "{{ repeat.item }}"
                    helper: "input_text.heizmodus_{{ entity|replace('.', '_') }}"
                    saved: "{{ states(entity) | default('heat', true) }}"

                - service: input_text.set_value
                  data:
                    entity_id: "{{ helper }}"
                    value: "{{ saved }}"

                - service: system_log.write
                  data:
                    message: "RESTORE: Speichere {{ saved }} für {{ entity }} → OFF"
                    level: info

                - service: climate.set_hvac_mode
                  target:
                    entity_id: "{{ entity }}"
                  data:
                    hvac_mode: "off"

      # ---------------------------------------------------------
      # FENSTER ZU → Restore (Tuya-sicher)
      # ---------------------------------------------------------
      - conditions:
          - condition: state
            entity_id: !input fenster
            state: "off"
        sequence:
          - repeat:
              for_each: "{{ heizkoerper }}"
              sequence:
                - variables:
                    entity: "{{ repeat.item }}"
                    helper: "input_text.heizmodus_{{ entity|replace('.', '_') }}"
                    saved: "{{ states(helper) | default('heat', true) }}"
                    modes: "{{ state_attr(entity, 'hvac_modes') | default([], true) }}"

                    zielmodus: >
                      {% if saved == 'off' %}
                        heat
                      {% elif saved == 'auto' and 'auto' in modes %}
                        auto
                      {% elif saved == 'heat' and 'heat' in modes %}
                        heat
                      {% elif 'heat' in modes %}
                        heat
                      {% else %}
                        none
                      {% endif %}

                - service: system_log.write
                  data:
                    message: >
                      RESTORE: {{ entity }} → gespeichert='{{ saved }}',
                      erlaubt='{{ modes }}', Ziel='{{ zielmodus }}'
                    level: info

                - choose:
                    - conditions:
                        - condition: template
                          value_template: "{{ zielmodus != 'none' }}"
                      sequence:
                        - service: climate.set_hvac_mode
                          target:
                            entity_id: "{{ entity }}"
                          data:
                            hvac_mode: "{{ zielmodus }}"
