blueprint:
  name: Fenster steuert Heizkörper (Zigbee-SAFE, Immer-AUTO + Helper)
  description: >
    Multi-Fensterkontakte, Hauptschalter, Area-basierte Heizungssteuerung.
    Zigbee-sicher: Modus wird VOR OFF gespeichert (heat/auto), aber nicht restored.
    Beim Schließen wird IMMER AUTO gesetzt.
  domain: automation

  input:
    fensterkontakte:
      name: Fensterkontakte
      selector:
        entity:
          domain: binary_sensor
          device_class:
            - window
            - door
            - opening
          multiple: true

    master_switch:
      name: Hauptschalter Heizung
      default: input_boolean.heizung_gesamt
      selector:
        entity:
          domain: input_boolean

mode: parallel

trigger:
  - platform: state
    entity_id: !input fensterkontakte
    to:
      - "on"
      - "off"

condition:
  - condition: state
    entity_id: !input master_switch
    state: "on"

action:

  # ---------------------------------------------------------
  # 1) YAML-Variablen
  # ---------------------------------------------------------
  - variables:
      fenster_liste: !input fensterkontakte

  # ---------------------------------------------------------
  # 2) Template-Variablen
  # ---------------------------------------------------------
  - variables:
      fenster: "{{ trigger.entity_id }}"
      is_window: "{{ fenster in fenster_liste }}"

  # ---------------------------------------------------------
  # 3) Fensteraktionen
  # ---------------------------------------------------------
  - choose:

      # ---------------------------------------------------------
      # FENSTER AUF → Modus speichern → OFF
      # ---------------------------------------------------------
      - conditions:
          - condition: template
            value_template: "{{ is_window and is_state(fenster, 'on') }}"
        sequence:

          # Area ermitteln
          - variables:
              area_id_val: "{{ area_id(fenster) }}"
              area_entities: "{{ area_entities(area_id_val) }}"
              heizkoerper: >
                {{ area_entities
                   | select('match', '^climate\\.')
                   | list }}

          # Modus speichern VOR OFF
          - repeat:
              for_each: "{{ heizkoerper }}"
              sequence:

                - variables:
                    entity: "{{ repeat.item }}"
                    helper: "input_text.heizmodus_{{ entity|replace('.', '_') }}"
                    current_mode: "{{ states(entity) }}"

                # Nur heat/auto speichern – niemals off
                - choose:
                    - conditions:
                        - condition: template
                          value_template: "{{ current_mode in ['heat','auto'] }}"
                      sequence:
                        - service: input_text.set_value
                          data:
                            entity_id: "{{ helper }}"
                            value: "{{ current_mode }}"

                # Jetzt OFF setzen
                - service: climate.set_hvac_mode
                  target:
                    entity_id: "{{ entity }}"
                  data:
                    hvac_mode: "off"

      # ---------------------------------------------------------
      # FENSTER ZU → IMMER AUTO (Zigbee-FIX)
      # ---------------------------------------------------------
      - conditions:
          - condition: template
            value_template: "{{ is_window and is_state(fenster, 'off') }}"
        sequence:

          # Area ermitteln
          - variables:
              area_id_val: "{{ area_id(fenster) }}"
              area_entities: "{{ area_entities(area_id_val) }}"
              heizkoerper: >
                {{ area_entities
                   | select('match', '^climate\\.')
                   | list }}

          # IMMER AUTO setzen (auch für Zigbee)
          - repeat:
              for_each: "{{ heizkoerper }}"
              sequence:
                - service: climate.set_hvac_mode
                  target:
                    entity_id: "{{ repeat.item }}"
                  data:
                    hvac_mode: "auto"
