blueprint:
  name: Fenster steuert Heizkörper (Multi, Master, Area, Zigbee-SAFE)
  description: >
    Multi-Fensterkontakte, Hauptschalter, Area-basierte Heizungssteuerung.
    Zigbee-sicher: Modus wird NICHT beim Fensteröffnen gespeichert,
    sondern automatisch getrackt, sobald er sich ändert.
    Restore setzt zuverlässig AUTO/HEAT, OFF wird nie restored.
  domain: automation

  input:
    fensterkontakte:
      name: Fensterkontakte
      selector:
        entity:
          domain: binary_sensor
          device_class:
            - window
            - door
            - opening
          multiple: true

    master_switch:
      name: Hauptschalter Heizung
      default: input_boolean.heizung_gesamt
      selector:
        entity:
          domain: input_boolean

mode: parallel

trigger:
  # Fensterkontakte
  - platform: state
    entity_id: !input fensterkontakte
    to:
      - "on"
      - "off"

  # Modus-Tracker: alle Climate-Entities im System
  - platform: state
    entity_id: >
      {{ states.climate | map(attribute='entity_id') | list }}

condition:
  - condition: state
    entity_id: !input master_switch
    state: "on"

action:

  # ---------------------------------------------------------
  # Gemeinsame Variablen (KEIN !input in Templates!)
  # ---------------------------------------------------------
  - variables:
      trigger_entity: "{{ trigger.entity_id }}"
      fenster_liste: !input fensterkontakte
      is_window: "{{ trigger_entity in fenster_liste }}"
      is_climate: "{{ trigger_entity.startswith('climate.') }}"

  # ---------------------------------------------------------
  # 1) MODUS-TRACKER (wenn ein Heizkörper sich ändert)
  # ---------------------------------------------------------
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ is_climate }}"
        sequence:
          - variables:
              helper: "input_text.heizmodus_{{ trigger_entity|replace('.', '_') }}"
              saved: "{{ states(trigger_entity) }}"
          - service: input_text.set_value
            data:
              entity_id: "{{ helper }}"
              value: "{{ saved }}"
          - service: system_log.write
            data:
              message: "Tracker: Speichere Modus {{ saved }} für {{ trigger_entity }}"
              level: info

  # ---------------------------------------------------------
  # 2) FENSTER-AKTIONEN (wenn ein Fenster triggert)
  # ---------------------------------------------------------
  - choose:

      # ---------------------------------------------------------
      # FENSTER AUF → OFF
      # ---------------------------------------------------------
      - conditions:
          - condition: template
            value_template: "{{ is_window and is_state(trigger_entity, 'on') }}"
        sequence:
          - variables:
              fenster_area: "{{ area_id(trigger_entity) }}"
              area_entities_list: "{{ area_entities(fenster_area) }}"
              heizkoerper: >
                {{ area_entities_list
                   | select('match', '^climate\\.')
                   | list }}

          - repeat:
              for_each: "{{ heizkoerper }}"
              sequence:
                - service: system_log.write
                  data:
                    message: "Fenster offen → OFF für {{ repeat.item }}"
                    level: info

                - service: climate.set_hvac_mode
                  target:
                    entity_id: "{{ repeat.item }}"
                  data:
                    hvac_mode: "off"

      # ---------------------------------------------------------
      # FENSTER ZU → Restore
      # ---------------------------------------------------------
      - conditions:
          - condition: template
            value_template: "{{ is_window and is_state(trigger_entity, 'off') }}"
        sequence:
          - variables:
              fenster_area: "{{ area_id(trigger_entity) }}"
              area_entities_list: "{{ area_entities(fenster_area) }}"
              heizkoerper: >
                {{ area_entities_list
                   | select('match', '^climate\\.')
                   | list }}

          - repeat:
              for_each: "{{ heizkoerper }}"
              sequence:
                - variables:
                    entity: "{{ repeat.item }}"
                    helper: "input_text.heizmodus_{{ entity|replace('.', '_') }}"
                    saved: "{{ states(helper) }}"
                    modes: "{{ state_attr(entity, 'hvac_modes') }}"

                    zielmodus: >
                      {% if saved == 'auto' and 'auto' in modes %}
                        auto
                      {% elif saved == 'heat' and 'heat' in modes %}
                        heat
                      {% elif 'heat' in modes %}
                        heat
                      {% else %}
                        none
                      {% endif %}

                - service: system_log.write
                  data:
                    message: >
                      Restore {{ entity }}:
                      gespeichert='{{ saved }}',
                      erlaubt='{{ modes }}',
                      Ziel='{{ zielmodus }}'
                    level: info

                - choose:
                    - conditions:
                        - condition: template
                          value_template: "{{ zielmodus != 'none' }}"
                      sequence:
                        - service: climate.set_hvac_mode
                          target:
                            entity_id: "{{ entity }}"
                          data:
                            hvac_mode: "{{ zielmodus }}"
