blueprint:
  name: Fenster steuert Heizkörper (Tuya-sicher & stabil)
  description: >
    Tuya-sichere Version: verhindert not_valid_hvac_mode.
    Off wird nie restored. Auto wird nur restored, wenn Tuya es erlaubt.
    Fallback = heat. Homematic bleibt voll kompatibel.
  domain: automation

  input:
    fensterkontakte:
      name: Fensterkontakte
      selector:
        entity:
          domain: binary_sensor
          device_class:
            - window
            - door
            - opening
          multiple: true

    master_switch:
      name: Hauptschalter Heizung
      default: input_boolean.heizung_gesamt
      selector:
        entity:
          domain: input_boolean

mode: parallel

trigger:
  - platform: state
    entity_id: !input fensterkontakte
    to:
      - "on"
      - "off"

condition:
  - condition: state
    entity_id: !input master_switch
    state: "on"

action:
  - variables:
      fenster: "{{ trigger.entity_id }}"
      fenster_area: "{{ area_id(fenster) }}"
      area_entities_list: "{{ area_entities(fenster_area) }}"
      heizkoerper: >
        {{ area_entities_list
           | select('match', '^climate\\.')
           | list }}

  - service: system_log.write
    data:
      message: >
        Fensteraktion: {{ fenster }} ({{ states(fenster) }}), Area: {{ fenster_area }},
        Heizkörper: {{ heizkoerper }}
      level: info

  - choose:

      # ---------------------------------------------------------
      # FENSTER AUF → Modus speichern + off
      # ---------------------------------------------------------
      - conditions:
          - condition: template
            value_template: "{{ is_state(fenster, 'on') }}"
        sequence:
          - repeat:
              for_each: "{{ heizkoerper }}"
              sequence:
                - variables:
                    entity: "{{ repeat.item }}"
                    helper: "input_text.heizmodus_{{ entity|replace('.', '_') }}"
                    raw_mode: "{{ states(entity) | default('heat', true) }}"
                    current_mode: "{{ raw_mode | string }}"

                - service: system_log.write
                  data:
                    message: "Speichere Modus für {{ entity }}: {{ current_mode }}"
                    level: info

                - service: input_text.set_value
                  data:
                    entity_id: "{{ helper }}"
                    value: "{{ current_mode }}"

                - service: climate.set_hvac_mode
                  target:
                    entity_id: "{{ entity }}"
                  data:
                    hvac_mode: "off"

      # ---------------------------------------------------------
      # FENSTER ZU → Tuya-sicheres Restore
      # ---------------------------------------------------------
      - conditions:
          - condition: template
            value_template: "{{ is_state(fenster, 'off') }}"
        sequence:
          - repeat:
              for_each: "{{ heizkoerper }}"
              sequence:
                - variables:
                    entity: "{{ repeat.item }}"
                    helper: "input_text.heizmodus_{{ entity|replace('.', '_') }}"
                    saved_raw: "{{ states(helper) | default('heat', true) }}"
                    modes: "{{ state_attr(entity, 'hvac_modes') | default([], true) }}"

                    # Tuya-sichere Restore-Logik:
                    # - off wird NIE restored
                    # - auto nur, wenn Tuya es erlaubt
                    # - fallback = heat
                    zielmodus: >
                      {% set valid = modes %}
                      {% if saved_raw == 'off' %}
                        heat
                      {% elif saved_raw == 'auto' and 'auto' in valid %}
                        auto
                      {% elif saved_raw == 'heat' and 'heat' in valid %}
                        heat
                      {% elif 'heat' in valid %}
                        heat
                      {% else %}
                        none
                      {% endif %}

                - service: system_log.write
                  data:
                    message: >
                      Restore für {{ entity }}:
                      gespeicherter Modus='{{ saved_raw }}',
                      verfügbare Modi='{{ modes }}',
                      Ziel='{{ zielmodus }}'
                    level: info

                - choose:
                    - conditions:
                        - condition: template
                          value_template: "{{ zielmodus != 'none' }}"
                      sequence:
                        - service: climate.set_hvac_mode
                          target:
                            entity_id: "{{ entity }}"
                          data:
                            hvac_mode: "{{ zielmodus }}"
