blueprint:
  name: Fenster Test – Area Minimal (OFF → HEAT)
  description: >
    Test 2: Fenster auf = OFF, Fenster zu = HEAT.
    Prüft, ob Zigbee AUTO blockiert, aber HEAT akzeptiert.
  domain: automation

  input:
    fenster:
      name: Fensterkontakt
      selector:
        entity:
          domain: binary_sensor
          device_class:
            - window
            - door
            - opening

mode: single

trigger:
  - platform: state
    entity_id: !input fenster
    to:
      - "on"
      - "off"

action:
  - variables:
      fenster_entity: "{{ trigger.entity_id }}"
      fenster_area: "{{ area_id(fenster_entity) }}"
      area_entities_list: "{{ area_entities(fenster_area) }}"
      heizkoerper: >
        {{ area_entities_list
           | select('match', '^climate\\.')
           | list }}

  - service: system_log.write
    data:
      message: >
        TEST2-HEAT: Fenster={{ fenster_entity }} ({{ states(fenster_entity) }}),
        Area={{ fenster_area }},
        Heizkörper={{ heizkoerper }}
      level: info

  - choose:

      # Fenster AUF → OFF
      - conditions:
          - condition: state
            entity_id: !input fenster
            state: "on"
        sequence:
          - repeat:
              for_each: "{{ heizkoerper }}"
              sequence:
                - service: system_log.write
                  data:
                    message: "TEST2-HEAT: Fenster AUF → OFF für {{ repeat.item }}"
                    level: info

                - service: climate.set_hvac_mode
                  target:
                    entity_id: "{{ repeat.item }}"
                  data:
                    hvac_mode: "off"

      # Fenster ZU → HEAT
      - conditions:
          - condition: state
            entity_id: !input fenster
            state: "off"
        sequence:
          - repeat:
              for_each: "{{ heizkoerper }}"
              sequence:
                - service: system_log.write
                  data:
                    message: "TEST2-HEAT: Fenster ZU → HEAT für {{ repeat.item }}"
                    level: info

                - service: climate.set_hvac_mode
                  target:
                    entity_id: "{{ repeat.item }}"
                  data:
                    hvac_mode: "heat"
