blueprint:
  name: Fenster steuert Heizkörper (Auto-Helper, Zigbee-SAFE, Immer-AUTO v2.01)
  description: >
    Multi-Fensterkontakte, Area-Erkennung, Zigbee-sicher.
    Modus wird VOR OFF gespeichert – automatisch pro Heizkörper.
    Beim Schließen wird IMMER AUTO gesetzt und das Sync-Script getriggert.
  domain: automation

  input:
    fensterkontakte:
      name: Fensterkontakte
      selector:
        entity:
          domain: binary_sensor
          device_class:
            - window
            - door
            - opening
          multiple: true

    master_switch:
      name: Hauptschalter Heizung
      default: input_boolean.heizung_gesamt
      selector:
        entity:
          domain: input_boolean

mode: parallel

trigger:
  - platform: state
    entity_id: !input fensterkontakte
    to:
      - "on"
      - "off"

condition:
  - condition: state
    entity_id: !input master_switch
    state: "on"

action:

  - variables:
      fenster_liste: !input fensterkontakte
      fenster: "{{ trigger.entity_id }}"
      is_window: "{{ fenster in fenster_liste }}"

  - choose:

      # ---------------------------------------------------------
      # FENSTER AUF → Modus speichern → OFF
      # ---------------------------------------------------------
      - conditions:
          - condition: template
            value_template: "{{ is_window and is_state(fenster, 'on') }}"
        sequence:

          - variables:
              area_id_val: "{{ area_id(fenster) }}"
              area_entities: "{{ area_entities(area_id_val) }}"
              heiz_liste: >
                {{ area_entities | select('match', '^climate\\.') | list }}

          - variables:
              erster_heizkoerper: "{{ heiz_liste[0] }}"
              aktueller_modus: "{{ states(erster_heizkoerper) }}"
              helper: "input_text.heizmodus_{{ erster_heizkoerper|replace('.', '_') }}"

          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ helper not in states }}"
                sequence:
                  - service: input_text.set_value
                    data:
                      entity_id: "{{ helper }}"
                      value: ""

          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ aktueller_modus in ['heat','auto'] }}"
                sequence:
                  - service: input_text.set_value
                    target:
                      entity_id: "{{ helper }}"
                    data:
                      value: "{{ aktueller_modus }}"

          - service: climate.set_hvac_mode
            target:
              entity_id: "{{ heiz_liste }}"
            data:
              hvac_mode: "off"

      # ---------------------------------------------------------
      # FENSTER ZU → IMMER AUTO + Sync-Script triggern
      # ---------------------------------------------------------
      - conditions:
          - condition: template
            value_template: "{{ is_window and is_state(fenster, 'off') }}"
        sequence:

          - variables:
              area_id_val: "{{ area_id(fenster) }}"
              area_entities: "{{ area_entities(area_id_val) }}"
              heiz_liste: >
                {{ area_entities | select('match', '^climate\\.') | list }}

          - service: climate.set_hvac_mode
            target:
              entity_id: "{{ heiz_liste }}"
            data:
              hvac_mode: "auto"

          # ⭐ WICHTIG: Event senden
          - event: fenster_bad_closed
