blueprint:
  name: Fenster Test – Ultra Minimal + Area FIX V2 + Restore Stufe 2 ZIGBEE-SAFE v2
  description: >
    Fenster auf = OFF (Modus speichern VOR dem Ausschalten, Zigbee-sicher).
    Fenster zu = gespeicherten Modus wiederherstellen.
    Verhindert Race-Conditions bei TS0601-Zigbee-Thermostaten.
  domain: automation

  input:
    fenster:
      name: Fensterkontakt
      selector:
        entity:
          domain: binary_sensor
          device_class:
            - window
            - door
            - opening

    modus_speicher:
      name: Helper zum Speichern des Modus
      selector:
        entity:
          domain: input_text

mode: single

trigger:
  - platform: state
    entity_id: !input fenster
    to:
      - "on"
      - "off"

action:

  - variables:
      fenster_entity: "{{ trigger.entity_id }}"
      fenster_area: "{{ area_id(fenster_entity) }}"
      area_entities_list: "{{ area_entities(fenster_area) }}"
      heizkoerper: >
        {{ area_entities_list
           | select('match', '^climate\\.')
           | list }}

  - choose:

      # ---------------------------------------------------------
      # FENSTER AUF → kurze Pause → Modus lesen → speichern → OFF
      # ---------------------------------------------------------
      - conditions:
          - condition: state
            entity_id: !input fenster
            state: "on"
        sequence:

          # Delay VOR dem Lesen des Modus (entscheidend!)
          - delay:
              milliseconds: 150

          - variables:
              heiz_liste: "{{ heizkoerper | list }}"
              erster_heizkoerper: "{{ heiz_liste[0] }}"
              aktueller_modus: "{{ states(erster_heizkoerper) }}"

          - service: input_text.set_value
            target:
              entity_id: !input modus_speicher
            data:
              value: "{{ aktueller_modus }}"

          - service: climate.set_hvac_mode
            target:
              entity_id: "{{ heiz_liste }}"
            data:
              hvac_mode: "off"

      # ---------------------------------------------------------
      # FENSTER ZU → gespeicherten Modus wiederherstellen
      # ---------------------------------------------------------
      - conditions:
          - condition: state
            entity_id: !input fenster
            state: "off"
        sequence:

          - variables:
              heiz_liste: "{{ heizkoerper | list }}"
              modus_speicher_entity: !input modus_speicher
              gespeicherter_modus: "{{ states(modus_speicher_entity) }}"

              restore_modus: >
                {% if gespeicherter_modus in ['auto', 'heat'] %}
                  {{ gespeicherter_modus }}
                {% else %}
                  auto
                {% endif %}

          - service: climate.set_hvac_mode
            target:
              entity_id: "{{ heiz_liste }}"
            data:
              hvac_mode: "{{ restore_modus }}"
