blueprint:
  name: Fenster steuert Heizkörper (AUTO wenn möglich, sonst HEAT – Zigbee-SAFE)
  description: >
    Multi-Fensterkontakte, Hauptschalter, Area-basierte Heizungssteuerung.
    Beim Öffnen: Heizkörper OFF. Beim Schließen: AUTO wenn verfügbar, sonst HEAT.
    Keine Helper, kein Restore, Zigbee-sicher.
  domain: automation

  input:
    fensterkontakte:
      name: Fensterkontakte
      selector:
        entity:
          domain: binary_sensor
          device_class:
            - window
            - door
            - opening
          multiple: true

    master_switch:
      name: Hauptschalter Heizung
      default: input_boolean.heizung_gesamt
      selector:
        entity:
          domain: input_boolean

mode: parallel

trigger:
  - platform: state
    entity_id: !input fensterkontakte
    to:
      - "on"
      - "off"

condition:
  - condition: state
    entity_id: !input master_switch
    state: "on"

action:

  # ---------------------------------------------------------
  # 1) YAML-Variablen
  # ---------------------------------------------------------
  - variables:
      fenster_liste: !input fensterkontakte

  # ---------------------------------------------------------
  # 2) Template-Variablen
  # ---------------------------------------------------------
  - variables:
      fenster: "{{ trigger.entity_id }}"
      is_window: "{{ fenster in fenster_liste }}"

  # ---------------------------------------------------------
  # 3) Fensteraktionen
  # ---------------------------------------------------------
  - choose:

      # ---------------------------------------------------------
      # FENSTER AUF → OFF
      # ---------------------------------------------------------
      - conditions:
          - condition: template
            value_template: "{{ is_window and is_state(fenster, 'on') }}"
        sequence:

          - variables:
              area_id_val: "{{ area_id(fenster) }}"
              area_entities: "{{ area_entities(area_id_val) }}"
              heizkoerper: >
                {{ area_entities
                   | select('match', '^climate\\.')
                   | list }}

          - repeat:
              for_each: "{{ heizkoerper }}"
              sequence:
                - service: climate.set_hvac_mode
                  target:
                    entity_id: "{{ repeat.item }}"
                  data:
                    hvac_mode: "off"

      # ---------------------------------------------------------
      # FENSTER ZU → AUTO wenn möglich, sonst HEAT
      # ---------------------------------------------------------
      - conditions:
          - condition: template
            value_template: "{{ is_window and is_state(fenster, 'off') }}"
        sequence:

          - variables:
              area_id_val: "{{ area_id(fenster) }}"
              area_entities: "{{ area_entities(area_id_val) }}"
              heizkoerper: >
                {{ area_entities
                   | select('match', '^climate\\.')
                   | list }}

          - repeat:
              for_each: "{{ heizkoerper }}"
              sequence:

                - variables:
                    entity: "{{ repeat.item }}"
                    modes: "{{ state_attr(entity, 'hvac_modes') }}"
                    zielmodus: >
                      {% if 'auto' in modes %}
                        auto
                      {% elif 'heat' in modes %}
                        heat
                      {% else %}
                        none
                      {% endif %}

                - choose:
                    - conditions:
                        - condition: template
                          value_template: "{{ zielmodus != 'none' }}"
                      sequence:
                        - service: climate.set_hvac_mode
                          target:
                            entity_id: "{{ entity }}"
                          data:
                            hvac_mode: "{{ zielmodus }}"
