blueprint:
  name: Fenster steuert Heizkörper (Multi, Master, Area, Zigbee-SAFE 2)
  description: >
    Multi-Fensterkontakte, Hauptschalter, Area-basierte Heizungssteuerung.
    Zigbee-sicher: Modus wird NICHT beim Fensteröffnen gespeichert.
    Restore setzt zuverlässig AUTO/HEAT, OFF wird nie restored.
  domain: automation

  input:
    fensterkontakte:
      name: Fensterkontakte
      selector:
        entity:
          domain: binary_sensor
          device_class:
            - window
            - door
            - opening
          multiple: true

    master_switch:
      name: Hauptschalter Heizung
      default: input_boolean.heizung_gesamt
      selector:
        entity:
          domain: input_boolean

mode: parallel

trigger:
  - platform: state
    entity_id: !input fensterkontakte
    to:
      - "on"
      - "off"

condition:
  - condition: state
    entity_id: !input master_switch
    state: "on"

action:

  # ---------------------------------------------------------
  # 1) YAML-Variablen (dürfen !input enthalten)
  # ---------------------------------------------------------
  - variables:
      fenster_liste: !input fensterkontakte

  # ---------------------------------------------------------
  # 2) Template-Variablen (KEIN !input erlaubt)
  # ---------------------------------------------------------
  - variables:
      trigger_entity: "{{ trigger.entity_id }}"
      is_window: "{{ trigger_entity in fenster_liste }}"

  # ---------------------------------------------------------
  # 3) Fensteraktionen
  # ---------------------------------------------------------
  - choose:

      # ---------------------------------------------------------
      # FENSTER AUF → OFF
      # ---------------------------------------------------------
      - conditions:
          - condition: template
            value_template: "{{ is_window and is_state(trigger_entity, 'on') }}"
        sequence:
          - variables:
              fenster_area: "{{ area_id(trigger_entity) }}"
              area_entities_list: "{{ area_entities(fenster_area) }}"
              heizkoerper: >
                {{ area_entities_list
                   | select('match', '^climate\\.')
                   | list }}

          - repeat:
              for_each: "{{ heizkoerper }}"
              sequence:
                - service: climate.set_hvac_mode
                  target:
                    entity_id: "{{ repeat.item }}"
                  data:
                    hvac_mode: "off"

      # ---------------------------------------------------------
      # FENSTER ZU → Restore
      # ---------------------------------------------------------
      - conditions:
          - condition: template
            value_template: "{{ is_window and is_state(trigger_entity, 'off') }}"
        sequence:
          - variables:
              fenster_area: "{{ area_id(trigger_entity) }}"
              area_entities_list: "{{ area_entities(fenster_area) }}"
              heizkoerper: >
                {{ area_entities_list
                   | select('match', '^climate\\.')
                   | list }}

          - repeat:
              for_each: "{{ heizkoerper }}"
              sequence:
                - variables:
                    entity: "{{ repeat.item }}"
                    helper: "input_text.heizmodus_{{ entity|replace('.', '_') }}"
                    saved: "{{ states(helper) }}"
                    modes: "{{ state_attr(entity, 'hvac_modes') }}"

                    zielmodus: >
                      {% if saved == 'auto' and 'auto' in modes %}
                        auto
                      {% elif saved == 'heat' and 'heat' in modes %}
                        heat
                      {% elif 'heat' in modes %}
                        heat
                      {% else %}
                        none
                      {% endif %}

                - choose:
                    - conditions:
                        - condition: template
                          value_template: "{{ zielmodus != 'none' }}"
                      sequence:
                        - service: climate.set_hvac_mode
                          target:
                            entity_id: "{{ entity }}"
                          data:
                            hvac_mode: "{{ zielmodus }}"
