blueprint:
  name: Fenster steuert Heizkörper (TESTVERSION – Fenster-ZU setzt immer AUTO)
  description: >
    Testversion: Beim Fenster-ZU wird IMMER direkt hvac_mode=auto gesetzt.
    Damit prüfen wir, ob der Restore-Block ausgeführt wird und ob Tuya den Modus akzeptiert.
  domain: automation

  input:
    fensterkontakte:
      name: Fensterkontakte
      selector:
        entity:
          domain: binary_sensor
          device_class:
            - window
            - door
            - opening
          multiple: true

    master_switch:
      name: Hauptschalter Heizung
      default: input_boolean.heizung_gesamt
      selector:
        entity:
          domain: input_boolean

mode: parallel

trigger:
  - platform: state
    entity_id: !input fensterkontakte
    to:
      - "on"
      - "off"

condition:
  - condition: state
    entity_id: !input master_switch
    state: "on"

action:
  - variables:
      fenster: "{{ trigger.entity_id }}"
      fenster_area: "{{ area_id(fenster) }}"
      area_entities_list: "{{ area_entities(fenster_area) }}"
      heizkoerper: >
        {{ area_entities_list
           | select('match', '^climate\\.')
           | list }}

  - service: system_log.write
    data:
      message: >
        Fensteraktion: {{ fenster }} ({{ states(fenster) }}), Area: {{ fenster_area }},
        Heizkörper: {{ heizkoerper }}
      level: info

  - choose:

      # ---------------------------------------------------------
      # FENSTER AUF → Heizkörper ausschalten
      # ---------------------------------------------------------
      - conditions:
          - condition: template
            value_template: "{{ is_state(fenster, 'on') }}"
        sequence:
          - repeat:
              for_each: "{{ heizkoerper }}"
              sequence:
                - variables:
                    entity: "{{ repeat.item }}"

                - service: system_log.write
                  data:
                    message: "TEST: Fenster AUF → Schalte {{ entity }} auf OFF"
                    level: info

                - service: climate.set_hvac_mode
                  target:
                    entity_id: "{{ entity }}"
                  data:
                    hvac_mode: "off"

      # ----------------------------------------------------------
      # FENSTER ZU → IMMER direkt AUTO setzen (Test)
      # ----------------------------------------------------------
      - conditions:
          - condition: template
            value_template: "{{ is_state(fenster, 'off') }}"
        sequence:
          - repeat:
              for_each: "{{ heizkoerper }}"
              sequence:
                - variables:
                    entity: "{{ repeat.item }}"

                - service: system_log.write
                  data:
                    message: "TEST: Fenster ZU → Setze {{ entity }} direkt auf AUTO"
                    level: info

                - service: climate.set_hvac_mode
                  target:
                    entity_id: "{{ entity }}"
                  data:
                    hvac_mode: "auto"
