blueprint:
  name: Fenster Test – Ultra Minimal + Area FIX V2 + Restore Stufe 2
  description: >
    Fenster auf = OFF (Modus speichern VOR dem Ausschalten).
    Fenster zu = gespeicherten Modus wiederherstellen.
    Zigbee-sicherer Modus-Speicher + Area-Erkennung.
  domain: automation

  input:
    fenster:
      name: Fensterkontakt
      selector:
        entity:
          domain: binary_sensor
          device_class:
            - window
            - door
            - opening

    modus_speicher:
      name: Helper zum Speichern des Modus
      selector:
        entity:
          domain: input_text

mode: single

trigger:
  - platform: state
    entity_id: !input fenster
    to:
      - "on"
      - "off"

action:
  - variables:
      fenster_entity: "{{ trigger.entity_id }}"
      fenster_area: "{{ area_id(fenster_entity) }}"
      area_entities_list: "{{ area_entities(fenster_area) }}"
      heizkoerper: >
        {{ area_entities_list
           | select('match', '^climate\\.')
           | list }}

  - service: system_log.write
    data:
      message: >
        RESTORE-STUFE-2: Fenster={{ fenster_entity }} ({{ states(fenster_entity) }}),
        Area={{ fenster_area }},
        Heizkörper={{ heizkoerper }}
      level: info

  - choose:

      # Fenster AUF → Modus speichern → OFF
      - conditions:
          - condition: state
            entity_id: !input fenster
            state: "on"
        sequence:
          - variables:
              heiz_liste: "{{ heizkoerper | list }}"
              erster_heizkoerper: "{{ heiz_liste[0] }}"
              aktueller_modus: "{{ states(erster_heizkoerper) }}"

          # Modus speichern (Zigbee-FIX: vor OFF)
          - service: input_text.set_value
            target:
              entity_id: !input modus_speicher
            data:
              value: "{{ aktueller_modus }}"

          # Jetzt erst OFF setzen
          - service: climate.set_hvac_mode
            target:
              entity_id: "{{ heiz_liste }}"
            data:
              hvac_mode: "off"

      # Fenster ZU → gespeicherten Modus wiederherstellen
      - conditions:
          - condition: state
            entity_id: !input fenster
            state: "off"
        sequence:
          - variables:
              heiz_liste: "{{ heizkoerper | list }}"
              gespeicherter_modus: "{{ states(!input modus_speicher) }}"

              # Zigbee-FIX: off niemals wiederherstellen → auto
              restore_modus: >
                {% if gespeicherter_modus in ['auto', 'heat'] %}
                  {{ gespeicherter_modus }}
                {% else %}
                  auto
                {% endif %}

          - service: system_log.write
            data:
              message: >
                RESTORE-STUFE-2: Wiederherstellung → {{ restore_modus }}
              level: info

          - service: climate.set_hvac_mode
            target:
              entity_id: "{{ heiz_liste }}"
            data:
              hvac_mode: "{{ restore_modus }}"
