blueprint:
  name: Fenster steuert Heizkörper (Area + Zigbee-kompatibel)
  description: >
    Area-basierte Heizungssteuerung. Zigbee/Tuya-kompatibel durch entity_id-Service-Calls.
    Off wird nie restored. Auto/Heat werden sicher gesetzt.
  domain: automation

  input:
    fensterkontakte:
      name: Fensterkontakte
      selector:
        entity:
          domain: binary_sensor
          device_class:
            - window
            - door
            - opening
          multiple: true

    master_switch:
      name: Hauptschalter Heizung
      default: input_boolean.heizung_gesamt
      selector:
        entity:
          domain: input_boolean

mode: parallel

trigger:
  - platform: state
    entity_id: !input fensterkontakte
    to:
      - "on"
      - "off"

condition:
  - condition: state
    entity_id: !input master_switch
    state: "on"

action:
  - variables:
      fenster: "{{ trigger.entity_id }}"
      fenster_area: "{{ area_id(fenster) }}"
      area_entities_list: "{{ area_entities(fenster_area) }}"
      heizkoerper: >
        {{ area_entities_list
           | select('match', '^climate\\.')
           | list }}

  - service: system_log.write
    data:
      message: >
        Fensteraktion: {{ fenster }} ({{ states(fenster) }}), Area: {{ fenster_area }},
        Heizkörper: {{ heizkoerper }}
      level: info

  - choose:

      # ---------------------------------------------------------
      # FENSTER AUF → Modus speichern + OFF
      # ---------------------------------------------------------
      - conditions:
          - condition: template
            value_template: "{{ is_state(fenster, 'on') }}"
        sequence:
          - repeat:
              for_each: "{{ heizkoerper }}"
              sequence:
                - variables:
                    entity: "{{ repeat.item }}"
                    helper: "input_text.heizmodus_{{ entity|replace('.', '_') }}"
                    saved: "{{ states(entity) | default('heat', true) }}"

                - service: input_text.set_value
                  data:
                    entity_id: "{{ helper }}"
                    value: "{{ saved }}"

                - service: system_log.write
                  data:
                    message: "Speichere Modus {{ saved }} für {{ entity }} und schalte OFF"
                    level: info

                # Zigbee/Tuya-sicher: entity_id statt device_id
                - service: climate.set_hvac_mode
                  target:
                    entity_id: "{{ entity }}"
                  data:
                    hvac_mode: "off"

      # ---------------------------------------------------------
      # FENSTER ZU → Restore (Tuya-sicher)
      # ---------------------------------------------------------
      - conditions:
          - condition: template
            value_template: "{{ is_state(fenster, 'off') }}"
        sequence:
          - repeat:
              for_each: "{{ heizkoerper }}"
              sequence:
                - variables:
                    entity: "{{ repeat.item }}"
                    helper: "input_text.heizmodus_{{ entity|replace('.', '_') }}"
                    saved: "{{ states(helper) | default('heat', true) }}"
                    modes: "{{ state_attr(entity, 'hvac_modes') | default([], true) }}"

                    zielmodus: >
                      {% if saved == 'off' %}
                        heat
                      {% elif saved == 'auto' and 'auto' in modes %}
                        auto
                      {% elif saved == 'heat' and 'heat' in modes %}
                        heat
                      {% elif 'heat' in modes %}
                        heat
                      {% else %}
                        none
                      {% endif %}

                - service: system_log.write
                  data:
                    message: >
                      Restore {{ entity }}:
                      gespeichert='{{ saved }}',
                      erlaubt='{{ modes }}',
                      Ziel='{{ zielmodus }}'
                    level: info

                - choose:
                    - conditions:
                        - condition: template
                          value_template: "{{ zielmodus != 'none' }}"
                      sequence:
                        # Zigbee/Tuya-sicher: entity_id statt device_id
                        - service: climate.set_hvac_mode
                          target:
                            entity_id: "{{ entity }}"
                          data:
                            hvac_mode: "{{ zielmodus }}"
