blueprint:
  name: Fenster steuert Heizkörper (Zigbee-SAFE, Immer-AUTO + Minimal-Helper)
  description: >
    Multi-Fensterkontakte, Area-Erkennung, Zigbee-sicher.
    Modus wird VOR OFF gespeichert – aber nur vom ERSTEN Heizkörper der Area (Minimal-Script-Logik).
    Beim Schließen wird IMMER AUTO gesetzt.
  domain: automation

  input:
    fensterkontakte:
      name: Fensterkontakte
      selector:
        entity:
          domain: binary_sensor
          device_class:
            - window
            - door
            - opening
          multiple: true

    master_switch:
      name: Hauptschalter Heizung
      default: input_boolean.heizung_gesamt
      selector:
        entity:
          domain: input_boolean

    modus_speicher:
      name: Helper zum Speichern des Modus
      selector:
        entity:
          domain: input_text

mode: parallel

trigger:
  - platform: state
    entity_id: !input fensterkontakte
    to:
      - "on"
      - "off"

condition:
  - condition: state
    entity_id: !input master_switch
    state: "on"

action:

  # ---------------------------------------------------------
  # 1) Variablen
  # ---------------------------------------------------------
  - variables:
      fenster_liste: !input fensterkontakte
      fenster: "{{ trigger.entity_id }}"
      is_window: "{{ fenster in fenster_liste }}"

  # ---------------------------------------------------------
  # 2) Fensteraktionen
  # ---------------------------------------------------------
  - choose:

      # ---------------------------------------------------------
      # FENSTER AUF → Modus speichern (nur erster Heizkörper) → OFF
      # ---------------------------------------------------------
      - conditions:
          - condition: template
            value_template: "{{ is_window and is_state(fenster, 'on') }}"
        sequence:

          # Area ermitteln
          - variables:
              area_id_val: "{{ area_id(fenster) }}"
              area_entities: "{{ area_entities(area_id_val) }}"
              heiz_liste: >
                {{ area_entities
                   | select('match', '^climate\\.')
                   | list }}

          # Nur ERSTEN Heizkörper verwenden (Minimal-Script-Logik)
          - variables:
              erster_heizkoerper: "{{ heiz_liste[0] }}"
              aktueller_modus: "{{ states(erster_heizkoerper) }}"

          # Modus speichern (nur heat/auto)
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ aktueller_modus in ['heat','auto'] }}"
                sequence:
                  - service: input_text.set_value
                    target:
                      entity_id: !input modus_speicher
                    data:
                      value: "{{ aktueller_modus }}"

          # Jetzt OFF setzen (für alle Heizkörper der Area)
          - service: climate.set_hvac_mode
            target:
              entity_id: "{{ heiz_liste }}"
            data:
              hvac_mode: "off"

      # ---------------------------------------------------------
      # FENSTER ZU → IMMER AUTO
      # ---------------------------------------------------------
      - conditions:
          - condition: template
            value_template: "{{ is_window and is_state(fenster, 'off') }}"
        sequence:

          - variables:
              area_id_val: "{{ area_id(fenster) }}"
              area_entities: "{{ area_entities(area_id_val) }}"
              heiz_liste: >
                {{ area_entities
                   | select('match', '^climate\\.')
                   | list }}

          - service: climate.set_hvac_mode
            target:
              entity_id: "{{ heiz_liste }}"
            data:
              hvac_mode: "auto"
