blueprint:
  name: Fenster Test – Ultra Minimal + Area FIX
  description: >
    Fenster auf = OFF, Fenster zu = AUTO.
    Ultra-minimal, aber mit Area-Erkennung und Zigbee-Fix.
    Keine Restore-Logik, keine Helper.
  domain: automation

  input:
    fenster:
      name: Fensterkontakt
      selector:
        entity:
          domain: binary_sensor
          device_class:
            - window
            - door
            - opening

mode: single

trigger:
  - platform: state
    entity_id: !input fenster
    to:
      - "on"
      - "off"

action:
  - variables:
      fenster_entity: "{{ trigger.entity_id }}"
      fenster_area: "{{ area_id(fenster_entity) }}"
      area_entities_list: "{{ area_entities(fenster_area) }}"
      heizkoerper: >
        {{ area_entities_list
           | select('match', '^climate\\.')
           | list }}

  - service: system_log.write
    data:
      message: >
        ULTRA-AREA-FIX: Fenster={{ fenster_entity }} ({{ states(fenster_entity) }}),
        Area={{ fenster_area }},
        Heizkörper={{ heizkoerper }}
      level: info

  - choose:

      # Fenster AUF → OFF
      - conditions:
          - condition: state
            entity_id: !input fenster
            state: "on"
        sequence:
          - repeat:
              for_each: "{{ heizkoerper }}"
              sequence:
                - service: climate.set_hvac_mode
                  target:
                    entity_id:
                      - "{{ repeat.item }}"
                  data:
                    hvac_mode: "off"

      # Fenster ZU → AUTO
      - conditions:
          - condition: state
            entity_id: !input fenster
            state: "off"
        sequence:
          - repeat:
              for_each: "{{ heizkoerper }}"
              sequence:
                - service: climate.set_hvac_mode
                  target:
                    entity_id:
                      - "{{ repeat.item }}"
                  data:
                    hvac_mode: "auto"
