blueprint:
  name: Fenster steuert Heizkörper (mit Modus-Speicherung & Auto-Helper + Logging)
  description: >
    Stabiler Blueprint mit Fallbacks für Homematic, Zigbee & Co.
  domain: automation

  input:
    fensterkontakte:
      name: Fensterkontakte
      selector:
        entity:
          domain: binary_sensor
          device_class:
            - window
            - door
            - opening
          multiple: true

    master_switch:
      name: Hauptschalter Heizung
      default: input_boolean.heizung_gesamt
      selector:
        entity:
          domain: input_boolean

mode: parallel

trigger:
  - platform: state
    entity_id: !input fensterkontakte
    to:
      - "on"
      - "off"

condition:
  - condition: state
    entity_id: !input master_switch
    state: "on"

action:
  - variables:
      fenster: "{{ trigger.entity_id }}"
      fenster_area: "{{ area_id(fenster) }}"
      area_entities_list: "{{ area_entities(fenster_area) }}"
      heizkoerper: >
        {{ area_entities_list
           | select('match', '^climate\\.')
           | list }}

  - service: system_log.write
    data:
      message: >
        Fensteraktion: {{ fenster }} ({{ states(fenster) }}), Area: {{ fenster_area }},
        Heizkörper: {{ heizkoerper }}
      level: info

  - choose:

      # ---------------------------------------------------------
      # FENSTER AUF
      # ---------------------------------------------------------
      - conditions:
          - condition: template
            value_template: "{{ is_state(fenster, 'on') }}"
        sequence:
          - repeat:
              for_each: "{{ heizkoerper }}"
              sequence:
                - variables:
                    entity: "{{ repeat.item }}"
                    helper: "input_text.heizmodus_{{ entity|replace('.', '_') }}"
                    raw_mode: "{{ state_attr(entity, 'hvac_mode') | default('heat', true) }}"
                    current_mode: "{{ raw_mode | string }}"
                - service: system_log.write
                  data:
                    message: "Speichere Modus für {{ entity }}: {{ current_mode }}"
                    level: info
                - service: input_text.set_value
                  data:
                    entity_id: "{{ helper }}"
                    value: "{{ current_mode | string }}"
                - service: climate.set_hvac_mode
                  data:
                    entity_id: "{{ entity }}"
                    hvac_mode: "off"

      # ---------------------------------------------------------
      # FENSTER ZU
      # ---------------------------------------------------------
      - conditions:
          - condition: template
            value_template: "{{ is_state(fenster, 'off') }}"
        sequence:
          - repeat:
              for_each: "{{ heizkoerper }}"
              sequence:
                - variables:
                    entity: "{{ repeat.item }}"
                    helper: "input_text.heizmodus_{{ entity|replace('.', '_') }}"
                    saved_raw: "{{ states(helper) | default('heat', true) }}"
                    modes: "{{ state_attr(entity, 'hvac_modes') | default([], true) }}"
                    saved: >
                      {% if saved_raw in modes %}
                        {{ saved_raw }}
                      {% elif 'auto' in modes %}
                        auto
                      {% elif 'heat' in modes %}
                        heat
                      {% else %}
                        heat
                      {% endif %}
                - service: system_log.write
                  data:
                    message: "Stelle Modus für {{ entity }} wieder her: {{ saved }}"
                    level: info
                - service: climate.set_hvac_mode
                  data:
                    entity_id: "{{ entity }}"
                    hvac_mode: "{{ saved }}"
