blueprint:
  name: Fenster Test – Area Minimal + Delay (OFF → AUTO)
  description: >
    Test 1: Fenster auf = OFF, Fenster zu = AUTO mit 0.5s Delay.
    Prüft, ob Zigbee den Moduswechsel erst nach kurzer Pause akzeptiert.
  domain: automation

  input:
    fenster:
      name: Fensterkontakt
      selector:
        entity:
          domain: binary_sensor
          device_class:
            - window
            - door
            - opening

mode: single

trigger:
  - platform: state
    entity_id: !input fenster
    to:
      - "on"
      - "off"

action:
  - variables:
      fenster_entity: "{{ trigger.entity_id }}"
      fenster_area: "{{ area_id(fenster_entity) }}"
      area_entities_list: "{{ area_entities(fenster_area) }}"
      heizkoerper: >
        {{ area_entities_list
           | select('match', '^climate\\.')
           | list }}

  - service: system_log.write
    data:
      message: >
        TEST1-DELAY: Fenster={{ fenster_entity }} ({{ states(fenster_entity) }}),
        Area={{ fenster_area }},
        Heizkörper={{ heizkoerper }}
      level: info

  - choose:

      # Fenster AUF → OFF
      - conditions:
          - condition: state
            entity_id: !input fenster
            state: "on"
        sequence:
          - repeat:
              for_each: "{{ heizkoerper }}"
              sequence:
                - service: system_log.write
                  data:
                    message: "TEST1-DELAY: Fenster AUF → OFF für {{ repeat.item }}"
                    level: info

                - service: climate.set_hvac_mode
                  target:
                    entity_id: "{{ repeat.item }}"
                  data:
                    hvac_mode: "off"

      # Fenster ZU → AUTO (mit Delay)
      - conditions:
          - condition: state
            entity_id: !input fenster
            state: "off"
        sequence:
          - delay: "00:00:00.5"

          - repeat:
              for_each: "{{ heizkoerper }}"
              sequence:
                - service: system_log.write
                  data:
                    message: "TEST1-DELAY: Fenster ZU → AUTO (0.5s Delay) für {{ repeat.item }}"
                    level: info

                - service: climate.set_hvac_mode
                  target:
                    entity_id: "{{ repeat.item }}"
                  data:
                    hvac_mode: "auto"
